/* Automatically generated by tree-sitter v0.25.3 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 12
#define LARGE_STATE_COUNT 3
#define SYMBOL_COUNT 11
#define ALIAS_COUNT 0
#define TOKEN_COUNT 5
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 3
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 3
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_comment = 1,
  sym_text = 2,
  sym_section_key = 3,
  anon_sym_COLON = 4,
  sym_source_file = 5,
  sym_section_value = 6,
  sym_title = 7,
  sym_section = 8,
  aux_sym_source_file_repeat1 = 9,
  aux_sym_section_value_repeat1 = 10,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_comment] = "comment",
  [sym_text] = "text",
  [sym_section_key] = "section_key",
  [anon_sym_COLON] = ":",
  [sym_source_file] = "source_file",
  [sym_section_value] = "section_value",
  [sym_title] = "title",
  [sym_section] = "section",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_section_value_repeat1] = "section_value_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_comment] = sym_comment,
  [sym_text] = sym_text,
  [sym_section_key] = sym_section_key,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_source_file] = sym_source_file,
  [sym_section_value] = sym_section_value,
  [sym_title] = sym_title,
  [sym_section] = sym_section,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_section_value_repeat1] = aux_sym_section_value_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_section_key] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_section_value] = {
    .visible = true,
    .named = true,
  },
  [sym_title] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_value_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_separator = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_separator] = "separator",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 3},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_key, 0},
    {field_separator, 1},
  [2] =
    {field_key, 0},
    {field_separator, 1},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(104);
      ADVANCE_MAP(
        ' ', 3,
        ':', 210,
        'D', 35,
        'G', 20,
        'H', 16,
        'P', 78,
        'R', 37,
        'S', 95,
        'T', 21,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '\n') SKIP(1);
      if (lookahead == 'H') ADVANCE(120);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(121);
      if (lookahead != 0) ADVANCE(208);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        ' ', 3,
        ':', 210,
        'D', 35,
        'G', 20,
        'H', 16,
        'P', 78,
        'R', 37,
        'S', 95,
        'T', 21,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(2);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        ' ', 3,
        ':', 210,
        'D', 36,
        'G', 20,
        'H', 16,
        'P', 78,
        'R', 37,
        'S', 95,
        'T', 21,
      );
      if (('\t' <= lookahead && lookahead <= '\r')) SKIP(2);
      END_STATE();
    case 4:
      if (lookahead == ' ') ADVANCE(18);
      END_STATE();
    case 5:
      if (lookahead == ' ') ADVANCE(105);
      END_STATE();
    case 6:
      if (lookahead == ' ') ADVANCE(13);
      END_STATE();
    case 7:
      if (lookahead == ' ') ADVANCE(12);
      END_STATE();
    case 8:
      if (lookahead == ' ') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == ' ') ADVANCE(17);
      END_STATE();
    case 10:
      if (lookahead == ' ') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == ':') ADVANCE(5);
      END_STATE();
    case 12:
      if (lookahead == 'B') ADVANCE(101);
      END_STATE();
    case 13:
      if (lookahead == 'C') ADVANCE(75);
      END_STATE();
    case 14:
      if (lookahead == 'C') ADVANCE(76);
      END_STATE();
    case 15:
      if (lookahead == 'D') ADVANCE(4);
      END_STATE();
    case 16:
      if (lookahead == 'G') ADVANCE(11);
      END_STATE();
    case 17:
      if (lookahead == 'P') ADVANCE(63);
      END_STATE();
    case 18:
      if (lookahead == 'P') ADVANCE(80);
      END_STATE();
    case 19:
      if (lookahead == 'R') ADVANCE(49);
      END_STATE();
    case 20:
      if (lookahead == 'S') ADVANCE(15);
      END_STATE();
    case 21:
      if (lookahead == 'a') ADVANCE(52);
      if (lookahead == 'e') ADVANCE(85);
      END_STATE();
    case 22:
      if (lookahead == 'a') ADVANCE(29);
      END_STATE();
    case 23:
      if (lookahead == 'a') ADVANCE(64);
      END_STATE();
    case 24:
      if (lookahead == 'a') ADVANCE(81);
      END_STATE();
    case 25:
      if (lookahead == 'a') ADVANCE(66);
      END_STATE();
    case 26:
      if (lookahead == 'a') ADVANCE(58);
      END_STATE();
    case 27:
      if (lookahead == 'b') ADVANCE(86);
      if (lookahead == 'm') ADVANCE(65);
      END_STATE();
    case 28:
      if (lookahead == 'b') ADVANCE(47);
      END_STATE();
    case 29:
      if (lookahead == 'c') ADVANCE(102);
      END_STATE();
    case 30:
      if (lookahead == 'c') ADVANCE(89);
      END_STATE();
    case 31:
      if (lookahead == 'c') ADVANCE(82);
      END_STATE();
    case 32:
      if (lookahead == 'c') ADVANCE(59);
      END_STATE();
    case 33:
      if (lookahead == 'd') ADVANCE(7);
      if (lookahead == 'r') ADVANCE(87);
      END_STATE();
    case 34:
      if (lookahead == 'd') ADVANCE(42);
      END_STATE();
    case 35:
      if (lookahead == 'e') ADVANCE(77);
      END_STATE();
    case 36:
      if (lookahead == 'e') ADVANCE(77);
      if (lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 37:
      if (lookahead == 'e') ADVANCE(97);
      END_STATE();
    case 38:
      if (lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 39:
      if (lookahead == 'e') ADVANCE(99);
      END_STATE();
    case 40:
      if (lookahead == 'e') ADVANCE(33);
      END_STATE();
    case 41:
      if (lookahead == 'e') ADVANCE(100);
      END_STATE();
    case 42:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 43:
      if (lookahead == 'e') ADVANCE(87);
      END_STATE();
    case 44:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 45:
      if (lookahead == 'e') ADVANCE(84);
      END_STATE();
    case 46:
      if (lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(83);
      END_STATE();
    case 48:
      if (lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 49:
      if (lookahead == 'e') ADVANCE(98);
      END_STATE();
    case 50:
      if (lookahead == 'f') ADVANCE(51);
      END_STATE();
    case 51:
      if (lookahead == 'f') ADVANCE(45);
      END_STATE();
    case 52:
      if (lookahead == 'g') ADVANCE(87);
      if (lookahead == 's') ADVANCE(62);
      END_STATE();
    case 53:
      if (lookahead == 'i') ADVANCE(28);
      END_STATE();
    case 54:
      if (lookahead == 'i') ADVANCE(96);
      END_STATE();
    case 55:
      if (lookahead == 'i') ADVANCE(39);
      END_STATE();
    case 56:
      if (lookahead == 'i') ADVANCE(88);
      END_STATE();
    case 57:
      if (lookahead == 'i') ADVANCE(23);
      END_STATE();
    case 58:
      if (lookahead == 'i') ADVANCE(72);
      END_STATE();
    case 59:
      if (lookahead == 'i') ADVANCE(43);
      END_STATE();
    case 60:
      if (lookahead == 'i') ADVANCE(74);
      END_STATE();
    case 61:
      if (lookahead == 'j') ADVANCE(46);
      END_STATE();
    case 62:
      if (lookahead == 'k') ADVANCE(87);
      END_STATE();
    case 63:
      if (lookahead == 'l') ADVANCE(25);
      END_STATE();
    case 64:
      if (lookahead == 'l') ADVANCE(8);
      END_STATE();
    case 65:
      if (lookahead == 'm') ADVANCE(24);
      END_STATE();
    case 66:
      if (lookahead == 'n') ADVANCE(209);
      END_STATE();
    case 67:
      if (lookahead == 'n') ADVANCE(34);
      END_STATE();
    case 68:
      if (lookahead == 'n') ADVANCE(90);
      END_STATE();
    case 69:
      if (lookahead == 'n') ADVANCE(32);
      END_STATE();
    case 70:
      if (lookahead == 'n') ADVANCE(92);
      END_STATE();
    case 71:
      if (lookahead == 'n') ADVANCE(91);
      END_STATE();
    case 72:
      if (lookahead == 'n') ADVANCE(48);
      END_STATE();
    case 73:
      if (lookahead == 'o') ADVANCE(61);
      END_STATE();
    case 74:
      if (lookahead == 'o') ADVANCE(66);
      END_STATE();
    case 75:
      if (lookahead == 'o') ADVANCE(70);
      END_STATE();
    case 76:
      if (lookahead == 'o') ADVANCE(71);
      END_STATE();
    case 77:
      if (lookahead == 'p') ADVANCE(38);
      END_STATE();
    case 78:
      if (lookahead == 'r') ADVANCE(54);
      END_STATE();
    case 79:
      if (lookahead == 'r') ADVANCE(209);
      END_STATE();
    case 80:
      if (lookahead == 'r') ADVANCE(73);
      END_STATE();
    case 81:
      if (lookahead == 'r') ADVANCE(101);
      END_STATE();
    case 82:
      if (lookahead == 'r') ADVANCE(53);
      END_STATE();
    case 83:
      if (lookahead == 'r') ADVANCE(87);
      END_STATE();
    case 84:
      if (lookahead == 'r') ADVANCE(44);
      END_STATE();
    case 85:
      if (lookahead == 's') ADVANCE(93);
      END_STATE();
    case 86:
      if (lookahead == 's') ADVANCE(31);
      END_STATE();
    case 87:
      if (lookahead == 's') ADVANCE(209);
      END_STATE();
    case 88:
      if (lookahead == 's') ADVANCE(60);
      END_STATE();
    case 89:
      if (lookahead == 't') ADVANCE(87);
      END_STATE();
    case 90:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 91:
      if (lookahead == 't') ADVANCE(26);
      END_STATE();
    case 92:
      if (lookahead == 't') ADVANCE(41);
      END_STATE();
    case 93:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 94:
      if (lookahead == 't') ADVANCE(10);
      END_STATE();
    case 95:
      if (lookahead == 'u') ADVANCE(27);
      END_STATE();
    case 96:
      if (lookahead == 'v') ADVANCE(22);
      END_STATE();
    case 97:
      if (lookahead == 'v') ADVANCE(55);
      END_STATE();
    case 98:
      if (lookahead == 'v') ADVANCE(56);
      END_STATE();
    case 99:
      if (lookahead == 'w') ADVANCE(40);
      END_STATE();
    case 100:
      if (lookahead == 'x') ADVANCE(94);
      END_STATE();
    case 101:
      if (lookahead == 'y') ADVANCE(209);
      END_STATE();
    case 102:
      if (lookahead == 'y') ADVANCE(6);
      END_STATE();
    case 103:
      if (eof) ADVANCE(104);
      if (lookahead == '\n') SKIP(103);
      if (lookahead == ' ') ADVANCE(108);
      if (lookahead == 'D') ADVANCE(141);
      if (lookahead == 'G') ADVANCE(125);
      if (lookahead == 'H') ADVANCE(120);
      if (lookahead == 'P') ADVANCE(184);
      if (lookahead == 'R') ADVANCE(142);
      if (lookahead == 'S') ADVANCE(200);
      if (lookahead == 'T') ADVANCE(126);
      if (('\t' <= lookahead && lookahead <= '\r')) ADVANCE(107);
      if (lookahead != 0) ADVANCE(208);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(105);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_text);
      ADVANCE_MAP(
        ' ', 108,
        'D', 141,
        'G', 125,
        'H', 120,
        'P', 184,
        'R', 142,
        'S', 200,
        'T', 126,
      );
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r')) ADVANCE(107);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(208);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_text);
      ADVANCE_MAP(
        ' ', 108,
        'D', 140,
        'G', 125,
        'H', 120,
        'P', 184,
        'R', 142,
        'S', 200,
        'T', 126,
      );
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r')) ADVANCE(107);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(208);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(123);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(117);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(116);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(124);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(122);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ' ') ADVANCE(118);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == ':') ADVANCE(106);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'B') ADVANCE(206);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'C') ADVANCE(180);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'C') ADVANCE(181);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'D') ADVANCE(109);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'G') ADVANCE(115);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'H') ADVANCE(120);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(121);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(208);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'P') ADVANCE(168);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'P') ADVANCE(185);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'R') ADVANCE(154);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'S') ADVANCE(119);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'a') ADVANCE(157);
      if (lookahead == 'e') ADVANCE(191);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'a') ADVANCE(134);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'a') ADVANCE(169);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'a') ADVANCE(186);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'a') ADVANCE(171);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'a') ADVANCE(163);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'b') ADVANCE(192);
      if (lookahead == 'm') ADVANCE(170);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'b') ADVANCE(152);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'c') ADVANCE(207);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'c') ADVANCE(195);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'c') ADVANCE(187);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'c') ADVANCE(164);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'd') ADVANCE(111);
      if (lookahead == 'r') ADVANCE(190);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'd') ADVANCE(147);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(182);
      if (lookahead == 'i') ADVANCE(155);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(182);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(202);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(172);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(204);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(138);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(205);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(174);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(190);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(173);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(189);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(135);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(188);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(183);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'e') ADVANCE(203);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'f') ADVANCE(156);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'f') ADVANCE(150);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'g') ADVANCE(190);
      if (lookahead == 's') ADVANCE(167);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'i') ADVANCE(133);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'i') ADVANCE(201);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'i') ADVANCE(144);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'i') ADVANCE(193);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'i') ADVANCE(128);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'i') ADVANCE(177);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'i') ADVANCE(148);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'i') ADVANCE(179);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'j') ADVANCE(151);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'k') ADVANCE(190);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'l') ADVANCE(130);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'l') ADVANCE(112);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'm') ADVANCE(129);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'n') ADVANCE(209);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'n') ADVANCE(139);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'n') ADVANCE(196);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'n') ADVANCE(137);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'n') ADVANCE(198);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'n') ADVANCE(197);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'n') ADVANCE(153);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'o') ADVANCE(166);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'o') ADVANCE(171);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'o') ADVANCE(175);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'o') ADVANCE(176);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'p') ADVANCE(143);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'r') ADVANCE(209);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'r') ADVANCE(159);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'r') ADVANCE(178);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'r') ADVANCE(206);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'r') ADVANCE(158);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'r') ADVANCE(190);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'r') ADVANCE(149);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 's') ADVANCE(209);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 's') ADVANCE(194);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 's') ADVANCE(136);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 's') ADVANCE(165);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 't') ADVANCE(113);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 't') ADVANCE(190);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 't') ADVANCE(162);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 't') ADVANCE(131);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 't') ADVANCE(146);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 't') ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'u') ADVANCE(132);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'v') ADVANCE(127);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'v') ADVANCE(160);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'v') ADVANCE(161);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'w') ADVANCE(145);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'x') ADVANCE(199);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'y') ADVANCE(209);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(sym_text);
      if (lookahead == 'y') ADVANCE(110);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(sym_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(sym_section_key);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 1},
  [2] = {.lex_state = 103},
  [3] = {.lex_state = 103},
  [4] = {.lex_state = 103},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_section_key] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(10),
    [sym_section_value] = STATE(8),
    [sym_title] = STATE(5),
    [aux_sym_section_value_repeat1] = STATE(3),
    [sym_comment] = ACTIONS(3),
    [sym_text] = ACTIONS(3),
  },
  [STATE(2)] = {
    [sym_section_value] = STATE(9),
    [aux_sym_section_value_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_comment] = ACTIONS(3),
    [sym_text] = ACTIONS(3),
    [sym_section_key] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      sym_section_key,
    STATE(4), 1,
      aux_sym_section_value_repeat1,
    ACTIONS(11), 2,
      sym_comment,
      sym_text,
  [14] = 4,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(20), 1,
      sym_section_key,
    STATE(4), 1,
      aux_sym_section_value_repeat1,
    ACTIONS(17), 2,
      sym_comment,
      sym_text,
  [28] = 3,
    ACTIONS(22), 1,
      ts_builtin_sym_end,
    ACTIONS(24), 1,
      sym_section_key,
    STATE(6), 2,
      sym_section,
      aux_sym_source_file_repeat1,
  [39] = 3,
    ACTIONS(24), 1,
      sym_section_key,
    ACTIONS(26), 1,
      ts_builtin_sym_end,
    STATE(7), 2,
      sym_section,
      aux_sym_source_file_repeat1,
  [50] = 3,
    ACTIONS(28), 1,
      ts_builtin_sym_end,
    ACTIONS(30), 1,
      sym_section_key,
    STATE(7), 2,
      sym_section,
      aux_sym_source_file_repeat1,
  [61] = 1,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      sym_section_key,
  [66] = 1,
    ACTIONS(35), 2,
      ts_builtin_sym_end,
      sym_section_key,
  [71] = 1,
    ACTIONS(37), 1,
      ts_builtin_sym_end,
  [75] = 1,
    ACTIONS(39), 1,
      anon_sym_COLON,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(3)] = 0,
  [SMALL_STATE(4)] = 14,
  [SMALL_STATE(5)] = 28,
  [SMALL_STATE(6)] = 39,
  [SMALL_STATE(7)] = 50,
  [SMALL_STATE(8)] = 61,
  [SMALL_STATE(9)] = 66,
  [SMALL_STATE(10)] = 71,
  [SMALL_STATE(11)] = 75,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 1),
  [7] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 2, 0, 1),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section_value, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section_value, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_value_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_value_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [20] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_section_value_repeat1, 2, 0, 0),
  [22] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [24] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [26] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [30] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_title, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, 0, 2),
  [37] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_hgcommit(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "hgcommit",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
